BlogBundle\Entity\Client:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\ClientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        createdAt:
            type: datetime
        expiresAt:
            type: datetime
    lifecycleCallbacks: {  }
